name: "Testing Action"
description: "This is a testing compositive action"
inputs:
  BEANSTALK_APP:  # application name
    description: 'BEANSTALK_APP'
    required: true
  BEANSTALK_ENV:  # environment name
    description: 'BEANSTALK_ENV'
    required: true
    default: 'devops'
outputs:
  BEANSTALK_APP: 
    description: "BEANSTALK_APP"
    value: ${{ steps.testing-action-id.outputs.BEANSTALK_APP }}
  BEANSTALK_ENV:
    description: "BEANSTALK_ENV"
    value: ${{ steps.testing-action-id.outputs.BEANSTALK_ENV }}

runs:
  using: "composite"
  steps:
    - name: Testing Action
      id: testing-action-id
      shell: bash
      run: | 
        echo "Testing Action Hello World"
        echo "::set-output name=BEANSTALK_APP::$(echo $BEANSTALK_APP)"
        echo "::set-output name=BEANSTALK_ENV::$(echo $BEANSTALK_ENV)"
